server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
#    defer-datasource-initialization: false

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5234/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

#  sql:
#    init:
#      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: fakemailfortestingpurpose@gmail.com
    password: rkqr wfgr ggjq semr
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com